language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '11'
  - '10'
  - '8'
before_script:
  - npm prune
script:
  - yarn run lint
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
